config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'

  # Override devise controller to use our custom RegistrationsController
  devise_for :users, :controllers => {registrations: 'registrations'}


  resources :users


  resources :movies

  get 'search', to: 'movies#search'

  root 'application#index'
  get 'application/index'

  resources :movies do
    resources :reviews
  end

  resources :reviews do
    resources :comments
  end

  resources :comments do
    resources :votes
      post "upvote", to: "votes#upvote_comment"
      post "downvote", to: "votes#downvote_comment"
  end

  resources :reviews do
    resources :votes
      post "upvote", to: "votes#upvote_review"
      post "downvote", to: "votes#downvote_review"
  end

  resources :movies do
    resources :votes
      post "rating", to: "votes#movie_rating"
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :review
  belongs_to :user

  has_many  :votes, as: :voteable
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true

  has_many  :reviews
  has_many  :votes, as: :voteable

end

app/models/movie_adapter.rb
class MovieAdapter
  def search(movie_title)
    key = ENV['API_AUTH_KEY']
    request = HTTParty.get("http://www.omdbapi.com/?t=#{movie_title}&apikey=#{key}").parsed_response
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :body, presence: true

  belongs_to :movie
  belongs_to :user
  has_many  :comments
  has_many  :votes, as: :voteable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :votes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to  :user
  belongs_to  :voteable, polymorphic: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def index
  #   @comments = Comment.all
  # end

  # def show
  #   @comment = Comment.find(params[:id])
  # end

  def new
    @review = Review.find(params[:review_id])
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @review = Review.find(params[:review_id])
    @movie = @review.movie
    @comment = @review.comments.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html {redirect_to movie_path(@movie)}
        format.js {redirect_to movie_path(@movie)}
      else
        format.html {redirect_to new_movie_comment_path(@review)}
      end
    end
  end

  def edit
    @review = Review.find(params[:review_id])
    @comment = Comment.find(params[:id])
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @review = Review.find(params[:review_id])
    @movie = @review.movie.id
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html {redirect_to movie_path(@movie)}
        format.js {redirect_to movie_path(@movie)}
      else
        format.html {redirect_to edit_review_comment_path(@movie, comment)}
      end
    end
  end

  def destroy
    @review = Review.find(params[:review_id])
    @comment = Comment.find(params[:id])
    @movie = @review.movie.id
    @comment.destroy

    redirect_to movie_path(@movie)
  end


  def comment_votes
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/concerns/votes_controller.rb
class VotesController < ApplicationController

  def upvote_comment
    @comment = Comment.find(params[:comment_id])
    @vote = @comment.votes.new(point:1)
    @vote.user_id = current_user.id
    @vote.save
    @movie = @comment.review.movie
    redirect_to(movie_path(@movie))
  end

  def downvote_comment
    @comment = Comment.find(params[:comment_id])
    @vote = @comment.votes.new(point:-1)
    @vote.user_id = current_user.id
    @vote.save
    @movie = @comment.review.movie
    redirect_to(movie_path(@movie))
  end

  def upvote_review
    @review = Review.find(params[:review_id])
    @vote = @review.votes.new(point:1)
    @vote.user_id = current_user.id
    @vote.save
    @movie = @review.movie
    redirect_to(movie_path(@movie))
  end

  def downvote_review
    @review = Review.find(params[:review_id])
    @vote = @review.votes.new(point:-1)
    @vote.user_id = current_user.id
    @vote.save
    @movie = @review.movie
    redirect_to(movie_path(@movie))
  end

  def movie_rating

    @movie = Movie.find(params[:movie_id])

    @score = (params[:star])

    @vote = @movie.votes.new(point: @score)
    @vote.user_id = current_user.id
    @vote.save
    redirect_to(movie_path(@movie))
  end


  private
  def vote_params
    params.require(:vote).permit(:user)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include ApplicationHelper

  def index
    if params[:genre]
      @genre = params[:genre]
      @movies = Movie.where('genre LIKE ?', "%#{@genre}%")
    elsif params[:rating]
      order = params[:rating]
      if order == "High"
        @movies = Movie.all.sort_by{|movie| movie.votes.average(:point)}.reverse
      else
        @movies = Movie.all.sort_by{|movie| movie.votes.average(:point)}
      end
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
    if @movie.votes.any?
      @rating = @movie.votes.where(voteable_type:"Movie").average(:point).round(1,:truncate)
    end
  end

  def search
      movie_title = params[:title]
      request = MovieAdapter.new.search(movie_title)
    if request["Response"] == "True"
      @movie = movie_title_search(request)
      redirect_to movie_path(@movie)
    else
      @error = "Incorrect spelling of movie title!"
      render 'application/index'
    end
  end




  private

  def movie_params
    params.require(:movie).permit(:title, :genre, :year, :actors, :directors)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

 def create
      super
      #Send email to the user when sign up
      UserMailer.welcome_email(@user).deliver
      @user.username = @user.email[/\w+@[a-zA-Z_]/][0..-3]
      @user.save
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:user, keys: [:username])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def index
  #   @reviews = Review.all
  # end

  # def show
  #   @review = Review.find(params[:id])
  # end

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.new(review_params)
    @review.user_id = current_user.id
    @review.save
    redirect_to movie_path(@movie)
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    render 'edit'
  end

  def update
    @review = Review.find(params[:id])
    @movie = @review.movie.id

    if @review.update(review_params)
      redirect_to movie_path(@movie)
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to movie_path(@movie)
  end

  private
  def review_params
    params.require(:review).permit(:body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

   def show
    @user = User.find(params[:id])
   end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
  end

  def update
    @user = User.find(params[:id])
    @user.super_user = true
    @user.save

    redirect_to user_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def movie_title_search(request)
    Movie.find_or_create_by(title: request["Title"], genre: request["Genre"], year: request["Year"], image_url: request["Poster"], actors: request["Actors"], director: request["Director"])
  end
end

app/views/application/index.html.erb
<div class="container">
	<div class="movie-search">
	<p class="error"><b><%= @error %></b></p>
	<h1 class="home-title">Movie Search</h1><br>
			<%= form_tag search_path, :method => 'get' do %>
			  <p>
			    <%= text_field_tag :title,  params[:title], placeholder: "What are you looking for?", size: 30 %>
			    <%= submit_tag "Search", :name => nil %>
			  </p>

			<% end %>
	</div>
</div>

app/views/comments/_edit.html.erb
<h1 class="white-text">Edit Comment</h1>

<%= form_for([@review, @comment], remote: true) do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<h1 class="white-text">New Comment</h1>

<%= form_for([@review, @review.comments.build], remote: true) do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <p class="white-text"><%= f.label :body %><br></p>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<div class="container box-it-out">
<!-- change path -->
<%= link_to 'Back', movies_path %>

<h1 class="white-text">Edit Comment</h1>

<%= form_for([@review, @comment]) do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/comments/edit.js.erb
$('#edit-comment-form').html("<%= j (render 'edit') %>");
$('#edit-comment-form').slideDown(350);

app/views/comments/new.html.erb
<div class="container box-it-out">
<!-- change path -->
<%= link_to 'Back', movies_path %>

<h1 class="white-text">New Comment</h1>

<%= form_for ([@review, @review.comments.build]) do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <p class="white-text"><%= f.label :body %><br></p>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/comments/new.js.erb
$('#new-comment-form').html("<%= j (render 'form') %>");
$('#new-comment-form').slideDown(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Favicon link -->
    <link rel="icon" href="https://pbs.twimg.com/profile_images/735861411289563136/CpLtg7bj.jpg" type="image" sizes="16x16">
    <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <title>Crabby Reviews</title>
  </head>


<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Crabby Reviews</a>
    </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Trending", movies_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if !user_signed_in? %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Signup", new_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
       <% end %>
    </div>
  </div>
</nav>

    <%= yield %>
</body>
<!-- <footer>
  <p>Available for non-commercial reuse only</p>
</footer> -->
</html>

app/views/movies/index.html.erb
<div class="container">

<!-- Spacial formatting div -->
<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>

<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 trending-movies">
<h1 class="white-text">Trending Movies</h1>

  <p class="white-text">Sort by Genre</p>
  <%= form_tag("/movies/index", method: "get") do %>

    <select name="genre">
      <option value="Comedy">Comedy</option>
      <option value=“Short”>Short</option>
      <option value="Drama">Drama</option>
      <option value="Adventure">Adventure</option>
      <option value="Animation">Animation</option>
      <option value="Sci-Fi">Sci-Fi</option>
      <option value="Thriller">Thriller</option>
      <option value="Action">Action</option>
      <option value="Horror">Horror</option>
      <option value="Western">Western</option>
      <option value="Mystery">Mystery</option>
      <option value="Crime">Crime</option>
    </select>
    <%= submit_tag("Sort") %>
    <% end %>
    <br>
    <p class="white-text">Sort by Rating</p>
  <%= form_tag("/movies/index", method: "get") do %>

    <select name="rating">
      <option value="High">Highest to Lowest</option>
      <option value=“Low”>Lowest to Highest</option>
    </select>
    <%= submit_tag("Sort") %>
    <% end %>
  </div>
  <!-- Spacial formatting div -->
  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>


  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 trending-movies-titles">
    <div class="trending-subtitle">
      <% if @genre %>
        <h3 class="white-text"><%= @genre %> Movies</h3>
      <% else %>
        <h3 class="white-text">Titles</h3>
      <% end %>
    </div>

    <ol>
      <% @movies.each do |movie| %>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
          <li class="order"><%= link_to "#{movie.title}", movie_path(movie) %></li>
        </div>
      <% end %>
      </ol>
  </div>

</div>

app/views/movies/show.html.erb
<div class="container box-it-out white-text">

<%= link_to 'Back', movies_path %>

<div style="margin-left: 0 auto">

<h1><%= @movie.title %></h1>
  <% if @movie.image_url != "N/A" %>
    <img src="<%= @movie.image_url %>">
  <% end %>
  <p><b>Genre</b>: <%= @movie.genre %></p>
  <p><b>Year</b>: <%= @movie.year %></p>
  <p><b>Actors</b>: <%= @movie.actors %></p>
  <p><b>Director</b>: <%= @movie.director %></p>
</div>

<% if @rating %>
  <h2 id="ratings-title"><%= @rating %> Stars</h2>
<% else %>
  <h2>There are no ratings for this movie</h2>
<% end %>

<% if user_signed_in? %>
  <%= form_tag(movie_rating_path(@movie)) do %>

    <%= radio_button_tag(:star, "1") %>
      <%= label_tag(:star1, "1") %>
    <%= radio_button_tag(:star, "2") %>
      <%= label_tag(:star2, "2") %>
    <%= radio_button_tag(:star, "3") %>
      <%= label_tag(:star3, "3") %>
    <%= radio_button_tag(:star, "4") %>
      <%= label_tag(:star4, "4") %>
    <%= radio_button_tag(:star, "5") %>
      <%= label_tag(:star5, "5") %>

    <p class="stars-submit">
       <%= submit_tag("Submit") %>
    </p>

  <% end %>
<% end %>




<% if  user_signed_in? && current_user.super_user?  %>
  <p class="review-text"><%= link_to 'Write A Review', new_movie_review_path(@movie) %></p>
<% end %><br><br><br>


                    <!-- REVIEW SECTION -->
<% @movie.reviews.each do |review| %>

<p class="review-text"><%= link_to "#{review.user.username}", user_path(review.user)%>'s review:
    <span><%= pluralize(review.votes.sum(:point), "votes") %></span>

<% if user_signed_in? && review.user_id == current_user.id %>
  <span class="btn"><%= link_to 'Edit', edit_movie_review_path(@movie, review) %></span>
    <span class="btn"><%= link_to 'Delete', movie_review_path(@movie, review),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></span>
<% end %>
<p class="review-text">"<%= review.body %>"</p>
</p>

   <%= pluralize(review.votes.sum(:point), "votes") %>
    <span class="vote-buttons"><%= button_to '+1', review_upvote_path(review), method: :post %></span>
    <span class="vote-buttons"><%= button_to '-1', review_downvote_path(review), method: :post %></span>




                  <!-- COMMENT SECTION -->
<% if user_signed_in? %>
<div id="new-comment-form">
  <%= link_to "Add a Comment", new_review_comment_path(review), remote: true %>
</div>
<% end %><br><br>

  <% review.comments.each do |comment| %>

<ul>
    <li><%= link_to "#{comment.user.username}", user_path(comment.user) %>'s comment: "<%= comment.body %>"

    <% if user_signed_in? && comment.user_id == current_user.id %>
      <span class="btn">
      <div id="edit-comment-form">
        <%= link_to 'Edit', edit_review_comment_path(review, comment), remote: true %></span>
      </div>
    <% end %>

    <% if user_signed_in? && (current_user.super_user? || comment.user_id == current_user.id) %>
      <span class="btn"><%= link_to 'Delete', review_comment_path(review, comment),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></span>
    <% end %>
<br>
        <span class="total-like-count"><%= pluralize(comment.votes.sum(:point), "votes") %></span>
        <div class="vote-buttons"><%= button_to '+1', comment_upvote_path(comment), method: :post %></div>
        <div class="vote-buttons"><%= button_to '-1', comment_downvote_path(comment), method: :post %></div>
    </li>
</ul>

  <% end %>
<% end %>


</div>

app/views/reviews/edit.html.erb
<div class="container box-it-out">
<!-- change path -->
<%= link_to 'Back', movies_path %>

<h1 class="white-text">Edit Review</h1>

<%= form_for ([@review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@review.errors.count, "error") %> prohibited
        this review from being saved:
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

</div>

app/views/reviews/new.html.erb
<div class="container box-it-out">
<!-- change path -->
<%= link_to 'Back', movies_path %>


<h1 class="white-text"> <%= @movie.title %> </h1>
<h2 class="white-text">New Review</h2>


<%= form_for ([@movie, @movie.reviews.build]) do |f| %>
  <% if @review.errors.any? %>
    <div class="white-text" id="error_explanation">
      <h2 class="white-text">
        <%= pluralize(@review.errors.count, "error") %> prohibited
        this review from being saved:
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li class="white-text"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <span class="white-text"><%= f.label :body %><br></span>
    <%= f.text_area :body, size: "80x5" %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container box-it-out">
<h1 class="white-text">All of our Crabby Users!</h1>


    <% @users.each do |user| %>
      <p class="white-text">
      <b><%= link_to "#{user.username}", user_path(user) %></b>
      </p>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="user-show">
  <div class="user-show-text">
    <h1><%= @user.username %></h1>
     <h2>Is a wonderful Crabby Movie Reviewer!! </h2>
     <p>  Need to reach them? </p>
          <%= @user.username %>'s email address is: <%= @user.email %>
     </p>


      <% if user_signed_in? && current_user.super_user? && !@user.super_user? %>
        <b><p style="font-size: 26px"><%= link_to "Make Super User", user_path(@user),
              method: :patch,
              data: { confirm: 'Are you sure?' } %></p></b>
      <% end %>

    </div>
</div>